spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyyMMdd HHmmss
server:
  port: 8122
  context-path: /customer-identification-system
  max-http-header-size: 8192
  tomcat:
    accept-count: 2000
    max-connections: 20000
    max-threads: 2000
    uri-encoding: UTF-8
    min-spare-threads: 200
    accesslog:
      directory: /data/logs/
      enabled: false
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 4000
    max-connections-per-route: 2000
  compression:
    request:
      min-request-size: 1024
      mime-types:
        - text/xml
        - application/xml
        - application/json
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
